---
database_file: "/home/chrisp/.timetrap.db"
round_in_seconds: 900
append_notes_delimiter: " "
formatter_search_paths:
- "/home/chrisp/.timetrap/formatters"
default_formatter: text
auto_sheet: dotfiles
auto_sheet_search_paths:
- "/home/chrisp/.timetrap/auto_sheets"
default_command:
auto_checkout: false
require_note: false
note_editor: "nvim"
week_start: Monday
