# Don't print a new line at the start of the prompt
add_newline = false
format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$custom\
$jobs\
$status\
$character"""
# $docker_context\
# $kubernetes\
# $package\
# $shlvl\
# $cmake\
# $dart\
# $elixir\
# $elm\
# $golang\
# $helm\
# $julia\
# $nim\
# $nodejs\
# $python\
# $rust\
# $terraform\
# $zig\
# $memory_usage\
# $env_var\
# $crystal\
# $aws\
# $username\
# $hostname\
# $cmd_duration\

[line_break]
disabled=true
# disabled=false

[aws]
disabled=true

[cmd_duration]
disabled=true

[hostname]
disabled=true

[username]
disabled=true

[python]
disabled=true

[rust]
disabled=true

[golang]
disabled=true

[memory_usage]
disabled=true

[nodejs]
disabled=true

[nim]
disabled=true

[dart]
disabled=true
# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "
vicmd_symbol = "[V](bold green) "

